target 'Starbucks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
end
