target 'Starbucks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sidedish

 pod 'SwiftLint'
 pod 'FirebaseAuth'
 pod 'GoogleSignIn'
 pod 'SnapKit', '~> 5.6.0'
end
